### PR TITLE
Feature add retries to test site bot

### PR DESCRIPTION
**Pull request by EhudPer**
Added to git ignore files,
And added to web checker to do 2 more tries before sending error mail if not receiving 200 status from a site.

Tested locally with intensional url that don't exists - and as excpeted this address only got a email of error.
After changing to real url the test worked and didn't send error email.

### CODE REVIEW

**Comment by EhudPer** [comment]
Closed and will reopen,
@pinkasey - form some reason instead of 1 commit and two changed files in my new branch -
it show that it has 33 commits and 9 files changes,
do you know how i can solve it and open a new pool request?.

**Comment by pinkasey** [comment]
@EhudPer 
look above :
> EhudPer wants to merge 33 commits into MaorUziel:master from animals-now:feature-add-retries-to-test-site-bot

That's the reason -
By default, when you open a PR in this repository, the base branch is `MaorUziel:master`. you want it to be `animals-now:master`

**Comment by EhudPer** [comment]
Thanks, i did as you told,
and now the new pr is as expected.
After it will be approved i'll test it on Jenkins.

‫בתאריך יום ג׳, 8 ביוני 2021 ב-8:08 מאת ‪Eyal Pinkas‬‏ <‪
***@***.***‬‏>:‬

**Comment by EhudPer** [comment]
https://github.com/animals-now/AnimalsTestBot/pull/7

‫בתאריך יום ה׳, 10 ביוני 2021 ב-13:47 מאת אהוד פרלמן <‪
***@***.***‬‏>:‬

**Pull request closed without merging**
